site_name: mytweepy
site_description: Velotio Hiring Task
repo_url: https://github.com/atmishra/velotio-task
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/atmishra">atmishra</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
