# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180426_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='screen_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
