# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180426_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
